# Generated by Django 5.1.6 on 2025-08-28 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_galleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='facebook',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='instagram',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='linkedin',
            field=models.URLField(blank=True, max_length=250, null=True),
        ),
    ]
