# Generated by Django 5.1.6 on 2025-09-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='role',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
