# Generated by Django 5.1.6 on 2025-09-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='day_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
