# Generated by Django 5.1.6 on 2025-09-11 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_match_day_number_match_venue'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='tournament1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
