# Generated by Django 5.1.6 on 2025-09-12 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0010_match_tournament1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchteamplayer',
            name='match',
        ),
        migrations.RemoveField(
            model_name='matchteamplayer',
            name='player',
        ),
        migrations.RemoveField(
            model_name='matchteamplayer',
            name='team',
        ),
        migrations.RemoveField(
            model_name='playerteam',
            name='player',
        ),
        migrations.RemoveField(
            model_name='playerteam',
            name='team',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='name',
            new_name='player_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='admin_dashboard.teamentry'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='tournaments',
            field=models.ManyToManyField(related_name='players', to='admin_dashboard.tournament'),
        ),
        migrations.AddField(
            model_name='teamentry',
            name='tournaments',
            field=models.ManyToManyField(related_name='teams', to='admin_dashboard.tournament'),
        ),
        migrations.AlterField(
            model_name='player',
            name='playing_role',
            field=models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All-rounder', 'All-rounder'), ('Wicket-Keeper', 'Wicket-Keeper')], max_length=50),
        ),
        migrations.AlterField(
            model_name='teamentry',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_entries/photos/'),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='MatchTeamPlayer',
        ),
        migrations.DeleteModel(
            name='PlayerTeam',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
